import {MonsterType} from "@/types";
import {Usable} from "@/constants/items/usalbe-item/usable-info";
import {Material} from "@/constants/items/material/material-info";

export const ScorchedSandsMonster = {
    SandRabbit: {
        icon: '🐇',
        name: '沙漠兔',
        description: '在炙熱的沙漠中跳躍,狩獵方式是一腳踢死獵物',
        level: 6,
        hp: 50,
        hpLimit: 50,
        ad: 11,
        adDefend: 5,
        apDefend: 5,
        hit: 10,
        dodge: 25,
        critRate: 25,
        critIncrease: 150,
        dropGold: 25,
        drop: [
            {item: Material.DesertRabbitMeat, chance: 0.3},
            {item: Material.LowerNormal, chance: 0.1},
        ]
    } as MonsterType,
    CactusSpirit: {
        icon: '🌵',
        name: '仙人掌精',
        description: '會走路的植物，防禦較高且渾身佈滿尖刺，會對攻擊者噴射尖刺',
        level: 6,
        hp: 50,
        hpLimit: 50,
        ad: 3,
        adDefend: 15,
        apDefend: 15,
        hit: 8,
        dodge: 0,
        critRate: 5,
        critIncrease: 150,
        chaseIncrease: -10,
        dropGold: 20,
        onAttacked: 'cactusSpiritOnAttacked',
        drop: [
            {item: Material.CactusMeat, chance: 0.3},
            {item: Material.CactusWater, chance: 0.05},
            {item: Material.LowerNormal, chance: 0.1},
        ]
    } as MonsterType,
    QuicksandWorm: {
        icon: '🪱',
        name: '流沙蟲',
        description: '在大地深處鑽洞的生物，動作難以捕捉',
        level: 7,
        ad: 13,
        hp: 80,
        hpLimit: 80,
        adDefend: 0,
        apDefend: 8,
        hit: 12,
        dodge: 20,
        critRate: 0,
        critIncrease: 100,
        dropGold: 20,
        drop: [
            {item: Material.SandWormBloodClot, chance: 0.3},
            {item: Material.LowerNormal, chance: 0.1},
        ]
    } as MonsterType,
    DesertScorpion: {
        icon: '🦂',
        name: '荒漠小蠍',
        description: '毒蠍的幼體，尾部的毒針閃爍著致命的冷光。',
        level: 8,
        hp: 30,
        hpLimit: 30,
        ad: 15,
        adDefend: 10,
        apDefend: 10,
        hit: 18,
        dodge: 5,
        critRate: 10,
        critIncrease: 200,
        dropGold: 20,
        onAttack: 'desertScorpionOnAttack',
        drop: [
            {item: Material.ScorpionShell, chance: 0.1},
            {item: Material.ScorpionBlackShell, chance: 0.05},
            {item: Material.LowerNormal, chance: 0.1},
        ],
    } as MonsterType,
    ArmoredVulture: {
        icon: '🦅',
        name: '鐵羽禿鷹',
        description: '在沙暴中穿梭的掠食者，雙翼硬如鋼鐵，衝鋒威力驚人。',
        level: 9,
        hp: 80,
        hpLimit: 80,
        ad: 18,
        adDefend: 0,
        apDefend: 0,
        hit: 25,
        dodge: 20,
        critRate: 20,
        critIncrease: 160,
        dropGold: 90,
        chaseIncrease: 30,
        drop: [
            {item: Material.VultureFeather, chance: 0.2},
            {item: Material.LowerNormal, chance: 0.1},
        ],
    } as MonsterType,
    SandRabbit2: {
        icon: '🐇',
        name: '沙漠獵兔',
        description: '更強大的沙漠兔,有高額閃避以及生存能力',
        level: 10,
        hp: 80,
        hpLimit: 80,
        ad: 10,
        adDefend: 5,
        apDefend: 5,
        hit: 10,
        dodge: 30,
        critRate: 25,
        critIncrease: 150,
        dropGold: 25,
        drop: [
            {item: Material.DesertRabbitMeat, chance: 0.5},
            {item: Material.LowerNormal, chance: 0.1},
        ]
    } as MonsterType,
    CactusSpirit2: {
        icon: '🌵',
        name: '沙塵仙人掌精',
        description: '表皮覆蓋黃色沙塵的仙人掌精，防禦較高且渾身佈滿尖刺，會對攻擊者噴射尖刺',
        level: 10,
        hp: 60,
        hpLimit: 60,
        ad: 3,
        adDefend: 17,
        apDefend: 17,
        hit: 8,
        dodge: 0,
        critRate: 5,
        critIncrease: 150,
        chaseIncrease: -10,
        dropGold: 20,
        onAttacked: 'cactusSpiritOnAttacked',
        drop: [
            {item: Material.CactusMeat, chance: 0.5},
            {item: Material.CactusWater, chance: 0.05},
            {item: Material.LowerNormal, chance: 0.1},
        ]
    } as MonsterType,
    QuicksandWorm2: {
        icon: '🪱',
        name: '大流沙蟲',
        description: '成年的流沙蟲，有高額血量以及傷害',
        level: 11,
        ad: 15,
        hp: 120,
        hpLimit: 120,
        adDefend: 0,
        apDefend: 8,
        hit: 12,
        dodge: 20,
        critRate: 0,
        critIncrease: 100,
        dropGold: 20,
        drop: [
            {item: Material.SandWormBloodClot, chance: 0.5},
            {item: Material.LowerNormal, chance: 0.1},
        ]
    } as MonsterType,
    DesertScorpion2: {
        icon: '🦂',
        name: '荒漠蠍',
        description: '毒蠍的成年體，尾部的毒針閃爍著致命的冷光。',
        level: 11,
        hp: 50,
        hpLimit: 50,
        ad: 15,
        adDefend: 12,
        apDefend: 12,
        hit: 18,
        dodge: 5,
        critRate: 10,
        critIncrease: 200,
        dropGold: 20,
        onAttack: 'desertScorpionOnAttack',
        drop: [
            {item: Material.ScorpionShell, chance: 0.2},
            {item: Material.ScorpionBlackShell, chance: 0.05},
            {item: Material.LowerNormal, chance: 0.1},
        ],
    } as MonsterType,
    DuneBeast: {
        icon: '🦖',
        name: '沙漠巨獸',
        description: '沙丘野生魔物中的領主，其吼聲能震落天上的飛鳥，但行動相對笨重，能跑就快跑吧!',
        class: 'elite big',
        level: 20,
        hp: 1000,
        hpLimit: 1000,
        ad: 50,
        adDefend: 20,
        apDefend: 20,
        hit: 25,
        dodge: 4,
        critRate: 20,
        critIncrease: 200,
        chaseIncrease: -100,
        dropGold: 500,
        drop: [
            {item: Material.BehemothHeart, chance: 0.5},
            {item: Material.LowerGiant, chance: 0.33},
        ],
        onDead: 'duneBeastOnDead',
        onStart: 'duneBeastOnStart',
        onAttacked: 'duneBeastOnAttacked',
    } as MonsterType,

}