import {MonsterType} from "@/types";

export const ScorchedSandsMonster = {
    SandRabbit: {
        icon: '🐇',
        name: '沙漠兔',
        description: '在炙熱的沙漠中跳躍,狩獵方式是一腳踢死獵物',
        level: 6,
        hp: 70,
        hpLimit: 70,
        ad: 22,
        adDefend: 10,
        apDefend: 5,
        hit: 10,
        dodge: 25,
        critRate: 25,
        critIncrease: 150,
        dropGold: 25,
    } as MonsterType,

    CactusSpirit: {
        icon: '🌵',
        name: '仙人掌精',
        description: '會走路的植物，渾身佈滿尖刺，防禦較高',
        level: 6,
        hp: 95,
        hpLimit: 95,
        ad: 20,
        adDefend: 5,
        apDefend: 20,
        hit: 8,
        dodge: 2,
        critRate: 5,
        critIncrease: 150,
        dropGold: 20,
    } as MonsterType,

    QuicksandWorm: {
        icon: '🪱',
        name: '流沙蟲',
        description: '在大地深處鑽洞的生物，動作難以捕捉',
        level: 7,
        hp: 120,
        hpLimit: 120,
        ad: 28,
        adDefend: 8,
        apDefend: 8,
        hit: 12,
        dodge: 10,
        critRate: 0,
        critIncrease: 100,
        dropGold: 20,
    } as MonsterType,

    DuneBeast: {
        icon: '🦖',
        name: '沙丘巨獸',
        description: '沙丘的領主，其吼聲能震落天上的飛鳥',
        class: 'elite big',
        level: 15,
        hp: 1000,
        hpLimit: 1000,
        ad: 50,
        adDefend: 30,
        apDefend: 30,
        hit: 25,
        dodge: 4,
        critRate: 20,
        critIncrease: 200,
        dropGold: 500,
    } as MonsterType,
}