// ⚔️ WEAPON (武器) - 主力輸出
import {EquipmentType} from "@/types";
import {EquipmentPosition} from "@/enums/enums";

export const Dagger = {
    Dagger0: {
        name: '生鏽匕首',
        description: '雖然破舊，但依舊鋒利。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        critRate: 10,
        ad: 3,
    } as EquipmentType,
    Dagger1: {
        name: '小刀',
        description: '普通的家用小刀。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        critRate: 13,
        ad: 6,
    } as EquipmentType,
    Dagger2: {
        name: '削皮刀',
        description: '刀刃很薄，切口整齊。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        critRate: 16,
        ad: 9,
    } as EquipmentType,
    Dagger3: {
        name: '鋼製短刀',
        description: '常見的冒險者配刀。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        critRate: 19,
        ad: 12,
    } as EquipmentType,
    Dagger4: {
        name: '折疊刀',
        description: '刀身厚實，結構穩定。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        critRate: 22,
        ad: 15,
    } as EquipmentType,
    Dagger5: {
        name: '黑色短匕',
        description: '漆黑的刀面不容易反光。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        critRate: 25,
        ad: 20,
    } as EquipmentType,
};

export const Sword = {
    Sword0: {
        name: '生鏽鐵劍',
        description: '雖然破舊，但依舊鋒利。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        ad: 5,
    } as EquipmentType,
    Sword1: {
        name: '鐵劍',
        description: '最基本的打鐵舖作品。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        ad: 10,
    } as EquipmentType,
    Sword2: {
        name: '長劍',
        description: '稍微重一點的鐵劍。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        ad: 15,
        hit: 5,
    } as EquipmentType,
    Sword3: {
        name: '鋼劍',
        description: '用比較好的鋼材打造。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        ad: 20,
        hit: 10,
    } as EquipmentType,
    Sword4: {
        name: '合金劍',
        description: '更精良的工藝,更多傷害。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        ad: 15,
        hit: 15,
    } as EquipmentType,
    Sword5: {
        name: '重型鋼劍',
        description: '加厚了護手的制式長劍。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        ad: 30,
        hit: 20,
    } as EquipmentType,
};

export const Axe = {
    Axe0: {
        name: '生鏽鐵斧',
        description: '有些破舊，拿來伐木剛剛好。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        hit: -10,
        ad: 7,
    } as EquipmentType,
    Axe1: {
        name: '銅斧',
        description: '進入銅器時代,武器更耐用',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        hit: -10,
        ad: 14,
    } as EquipmentType,
    Axe2: {
        name: '鋼鐵斧',
        description: '換了鋼製刃部，更耐用了。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        hit: -10,
        ad: 21,
    } as EquipmentType,
    Axe3: {
        name: '鋼鐵斧',
        description: '換了鋼製刃部，更耐用了。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        hit: -10,
        ad: 28,
        critIncrease: 10
    } as EquipmentType,
    Axe4: {
        name: '雙手斧',
        description: '需要兩隻手才能拿穩。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        hit: -10,
        ad: 35,
        critIncrease: 15
    } as EquipmentType,
    Axe5: {
        name: '大鐵斧',
        description: '巨大的斧頭，看起來很嚇人。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        hit: -10,
        ad: 45,
        critIncrease: 20
    } as EquipmentType,
};

export const MagicStick = {
    MagicStick0: {
        name: '陳舊法杖',
        description: '有些許魔力附著在上面。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        apIncrease: 10,
    } as EquipmentType,
    MagicStick1: {
        name: '普通法杖',
        description: '經過打磨的法力樹枝，還算順手。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        apIncrease: 15,
        spLimit: 20,
    } as EquipmentType,
    MagicStick2: {
        name: '學徒法杖',
        description: '刻有簡易銘文的木杖，是法術入門者的標準配置。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        apIncrease: 20,
        spLimit: 40,
    } as EquipmentType,
    MagicStick3: {
        name: '鑲星圓杖',
        description: '杖頭鑲嵌了磨損的晶石，能微弱地感應周遭元素。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        apIncrease: 25,
        spLimit: 60,
    } as EquipmentType,
    MagicStick4: {
        name: '螢石靈木杖',
        description: '古老木材與螢石的結合，原石中隱約流動著魔力的光脈。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        apIncrease: 30,
        spLimit: 80,
    } as EquipmentType,
    MagicStick5: {
        name: '精鋼秘法杖',
        description: '以精鍊鋼材打造，冷冽的金屬表面極大化了魔力的傳導效率。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        apIncrease: 35,
        spLimit: 100,
    } as EquipmentType,
};
const SpecialWeapon = {
    SpikeSpear: {
        name: '尖刺木槍',
        icon: '🪾',
        description: '從枯死的魔樹枝幹削製而成的尖刺長槍,但使用時會奪去部分生命。',
        position: EquipmentPosition.WEAPON,
        ad: 10,
        hpLimit: -50,
        critRate: 10,
        hit: 5,
        quality: 11
    } as EquipmentType,
}

export const Weapon = {...Dagger, ...Sword, ...MagicStick, ...Axe, ...SpecialWeapon}